#!/usr/bin/env bash

while true; do
  artist=$(spotify-now-playing --artist 2>/dev/null)
  title=$(spotify-now-playing --title 2>/dev/null)

  if [[ $artist = "" || $title = "" ]]; then
    echo "Spotify offline"
    sleep 3
  else
    echo "$title" by "$artist"
    sleep 1
  fi

done
