#!/usr/bin/env bash

while true; do
  artist=$(spotify-cli status --kind artist 2>/dev/null)
  title=$(spotify-cli status --kind title 2>/dev/null)

  if [[ $artist = "" || $title = "" ]]; then
    echo "Spotify offline"
    sleep 3
  else
    echo "$title" by "$artist"
    sleep 1
  fi
done
